### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by chemhong** [alesandroLang/docker-django#11]
Thank you so much for your contribution, i am quite new on docker and I faced some problems on pull the image to run it on NAS. The listed below are the log, could you give me some ideas to fix it, thanks.

ModuleNotFoundError: No module named '.wsgi'
--
 __import__(module)
File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
return util.import_app(self.app_uri)
 File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
 return self.load_wsgiapp()
 File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
 self.callable = self.load()
File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
 self.load_wsgi()
 File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
 worker.init_process()
 File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
 Traceback (most recent call last):
[ERROR] Exception in worker process
starting gunicorn (PORT=8000, RELOAD=false, APP=)

**Comment by alesandroLang** [comment]
Hi chemhong,

please have a look at #9.
