### ISSUE TITLE
Cannot Start Docker

### ISSUE THREAD

**Issue by SiliconXu** [alesandroLang/docker-django#24]
Hi,

I'm using Unraid and try to start the image after downloading it. But it won't start. I checked the log and it says in the end of the log (please let me know if you need the full log):
TypeError: the 'package' argument is required to perform a relative import for '.wsgi'

Can you please help with this? (is it possible I did not set the path and variable correctly? If yes, how should I set them up?)

Thanks a lot!

**Comment by alesandroLang** [comment]
Hi SiliconXu,

I also do think that either your PATH or your directory structure within the container is not correct.

I would suggest to start with a simple Dockerfile like this and then incrementally apply your changes if needed.
```
FROM alang/django
ENV DJANGO_APP=demo                # will start /usr/django/app/demo/wsgi.py
COPY src /usr/django/app
```

**Comment by SiliconXu** [comment]
Hi alesandroLang,

Thanks for your quick respond!
I'm new to Unraid and Docker. Could please kindly advise the steps of how to run (or edit) the Dockerfile? I try to google it and found nothing (might be because this it too basic to be worthy of discussing 😂 )

**Comment by alesandroLang** [comment]
Hi SiliconXu,

I already pasted the simplest Dockerfile you could use.
It assumes your Django code is inside the "src" directory next to the Dockerfile.

For more information about Docker in general. Please read the docs on the Docker website.
