### ISSUE TITLE
How run "django-admin startproject mysite" with your solution ?

### ISSUE THREAD

**Issue by fletort** [alesandroLang/docker-django#3]

**Comment by alesandroLang** [comment]
You can create a throwaway container for this purpose:

    docker run --rm -v "$(PWD)/src:/usr/django/app" alang/django /bin/bash -c 'django-admin startproject mysite app'

As an alternative you can always use interactive pseudo TTY by running `/bin/bash` and do your setup work this way.

Hope this helps :)

**Comment by fletort** [comment]
ok thanks it's working for me
