### ISSUE TITLE
How serve static file ?

### ISSUE THREAD

**Issue by fletort** [alesandroLang/docker-django#4]
Ok, it's great, but in this solution (gunicorn tool only, no nginx), how serve the static file ?
not found: /static/admin/.....

**Comment by alesandroLang** [comment]
All static files are going to `/var/www/static` which is marked as a docker volume.
So just spin up **another container like nginx** for example and serve the static files from the volume.

Hope this helps :)

**Comment by fletort** [comment]
How default static files (coming with django) can be copied there ?

**Comment by alesandroLang** [comment]
If the environment variable `DJANGO_COLLECTSTATIC` is set to `true` the container will execute `python manage.py collectstatic --noinput` on start.

So you only have to point your `STATIC_ROOT` setting in `settings.py` to `/var/www/static`.

**Comment by alesandroLang** [comment]
I am closing this issue now.
Feel free to reopen it if you have any further questions.
