### ISSUE TITLE
Where is the django site?

### ISSUE THREAD

**Issue by erikbgithub** [alesandroLang/docker-django#5]
Hi Alesandro,

as I understand it this image is prepared to just drop a django app, right? But where is the django site, with the settings.py, the wsgi file, etc?

It would make things probably understandable if there would be a hello world app already there that people know where to just drop the app code to not worry about the django site at all.

Thanks.

**Comment by erikb85** [comment]
I think I get it that a "django app" in your README is not the same as an "app" for django, but the django site. However, if one wants to create a project in `/usr/django/app` then this is overwritten by your [onbuild copy](https://github.com/alesandroLang/docker-django/blob/master/1.10/python3/onbuild/Dockerfile#L4). Which is executed after all steps in the user's Dockerfile.

**Comment by alesandroLang** [comment]
Hi Erik,

you are right that `usr/django/app` should contain the django site.
Improvements to the README file or a example project are always appreciated as PR :)

Regarding the onbuild image the behaviour should be ok provided that this directory is setup as a [volume](https://github.com/alesandroLang/docker-django/blob/master/1.10/python3/Dockerfile#L17). I use the volume to keep the directory in sync with my local project folder.
 
Any issues with that?

**Comment by alesandroLang** [comment]
I am closing this issue now.
Feel free to reopen it if you have any further questions.
