### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by DocteurNo** [alesandroLang/docker-django#8]
I can not start the server on localhost: 8000, it does not work, What command should I have to start runserver.

Translated with google, I'm french

**Comment by alesandroLang** [comment]
Hi,

please provide some log messages and describe your setup more in detail.

Just to clarify:
This Docker image does not use the Django `runserver` command - Gunicorn is used instead.
Gunicorn should be started automaitcally because there is a `CMD` instruction which the Dockerfile.
