### ISSUE TITLE
ModuleNotFoundError: No module named '.wsgi'

### ISSUE THREAD

**Issue by CartierPierre** [alesandroLang/docker-django#9]
Hi, I'm new with Docker and Django,
I builded your image but I have this error

`ModuleNotFoundError: No module named '.wsgi'`

It's probably from gunicorn but I don't know how it works.

I'm using docker for windows (shame on me)

**Comment by alesandroLang** [comment]
Hi Pierre,

this error usually occurs if the `wsgi.py` file is missing or not in the correct directory.
The file should have been generated by the `startproject` command.

As mentioned in the README the enviormnet variable `DJANGO_APP` specifies where the file should be located.

Here is an example Dockerfile:

```
FROM alang/django
ENV DJANGO_APP=demo                # will start /usr/django/app/demo/wsgi.py
COPY src /usr/django/app
```

Hope this helps :)
